name: Playwright

on:
  repository_dispatch:
    types:
      - 'vercel.deployment.success'
  schedule:
    # Runs at the minute 30 of every hour
    - cron: '30 0/1 * * *'

jobs:
  e2e:
    name: 'E2E'
    # Only run on a Preview or Production deployment.
    if: ${{ github.event_name == 'schedule' || (github.event_name == 'repository_dispatch' }}
    uses: ./.github/workflows/playwright-reusable.yml
    with:
      test-type: 'e2e'
    secrets: inherit

  integration:
    name: Integration
    if: ${{ github.event_name == 'schedule' || (github.event_name == 'repository_dispatch' }}
    uses: ./.github/workflows/playwright-reusable.yml
    with:
      test-type: 'integration'
    secrets: inherit
